USER_ROLES = ["USER", "DRIVER", "ADMIN"]
DRIVER_STATUSES = ["AVAILABLE", "BUSY", "OFFLINE"]
AMBULANCE_STATUSES = ["AVAILABLE", "ASSIGNED", "EN_ROUTE", "OFFLINE"]
AMBULANCE_TYPES = ["BASIC", "ADVANCED", "ICU"]
HOSPITAL_STATUSES = ["ACTIVE", "FULL", "INACTIVE"]

TRIP_STATUS_FLOW = [
    "REQUESTED",
    "ASSIGNED",
    "ACCEPTED",
    "EN_ROUTE",
    "ARRIVED_AT_PATIENT",
    "PATIENT_PICKED_UP",
    "EN_ROUTE_TO_HOSPITAL",
    "ARRIVED_AT_HOSPITAL",
    "COMPLETED",
]
